CREATE TABLE CENTROS_CUSTOS (
    ID_CENTRO_CUSTO       BIGINT GENERATED ALWAYS AS IDENTITY,
    CODIGO                VARCHAR(30) NOT NULL,
    NOME                  VARCHAR(150) NOT NULL,
    DESCRICAO             VARCHAR(500),
    ATIVO                 BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO      TIMESTAMP,

    CONSTRAINT PK_CENTROS_CUSTOS
        PRIMARY KEY (ID_CENTRO_CUSTO),

    CONSTRAINT UK_CENTRO_CUSTO_CODIGO
        UNIQUE (CODIGO)
);