CREATE TABLE CLIENTES (
    ID_CLIENTE          BIGINT GENERATED ALWAYS AS IDENTITY,
    NOME_RAZAO_SOCIAL   VARCHAR(200) NOT NULL,
    TIPO_PESSOA         VARCHAR(20) NOT NULL,
    CPF_CNPJ            VARCHAR(18),
    EMAIL               VARCHAR(255),
    TELEFONE            VARCHAR(20),
    ENDERECO            VARCHAR(300),
    CIDADE              VARCHAR(100),
    UF                  CHAR(2),
    CEP                 VARCHAR(10),
    ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP,

    CONSTRAINT PK_CLIENTES
        PRIMARY KEY (ID_CLIENTE),

    CONSTRAINT UK_CLIENTE_CPF_CNPJ
        UNIQUE (CPF_CNPJ),

    CONSTRAINT CK_CLIENTE_TIPO_PESSOA
        CHECK (TIPO_PESSOA IN ('FISICA', 'JURIDICA'))
);