CREATE TABLE CONTA_FINANCEIRA (
    ID_CONTA_FINANCEIRA     BIGINT GENERATED ALWAYS AS IDENTITY,
    ID_TIPO_CONTA           BIGINT NOT NULL,
    NOME                    VARCHAR(150) NOT NULL,
    BANCO                   VARCHAR(100),
    AGENCIA                 VARCHAR(20),
    NUMERO_CONTA            VARCHAR(30),
    DIGITO_CONTA            VARCHAR(5),
    SALDO_INICIAL           NUMERIC(15,2) NOT NULL DEFAULT 0,
    DATA_SALDO_INICIAL      DATE,
    ATIVO                   BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO        TIMESTAMP,

    CONSTRAINT PK_CONTA_FINANCEIRA
        PRIMARY KEY (ID_CONTA_FINANCEIRA),

    CONSTRAINT FK_CONTA_TIPO
        FOREIGN KEY (ID_TIPO_CONTA)
        REFERENCES TIPO_CONTA (ID_TIPO_CONTA),

    CONSTRAINT CK_CONTA_SALDO_INICIAL
        CHECK (SALDO_INICIAL >= 0)
);