CREATE TABLE CONTAS_CONTABEIS (
    ID_CONTA_CONTABIL      BIGINT GENERATED ALWAYS AS IDENTITY,
    ID_CONTA_PAI           BIGINT,
    CODIGO                 VARCHAR(30) NOT NULL,
    NOME                   VARCHAR(200) NOT NULL,
    TIPO                   VARCHAR(20) NOT NULL,
    DESCRICAO              VARCHAR(500),
    ATIVO                  BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO       TIMESTAMP,

    CONSTRAINT PK_CONTAS_CONTABEIS
        PRIMARY KEY (ID_CONTA_CONTABIL),

    CONSTRAINT FK_CONTA_CONTABIL_PAI
        FOREIGN KEY (ID_CONTA_PAI)
        REFERENCES CONTAS_CONTABEIS (ID_CONTA_CONTABIL),

    CONSTRAINT UK_CONTA_CONTABIL_CODIGO
        UNIQUE (CODIGO),

    CONSTRAINT CK_CONTA_CONTABIL_TIPO
        CHECK (TIPO IN ('RECEITA', 'DESPESA', 'ATIVO', 'PASSIVO', 'PATRIMONIO'))
);