CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO     BIGINT GENERATED ALWAYS AS IDENTITY,
    NOME                   VARCHAR(100) NOT NULL,
    DESCRICAO              VARCHAR(300),
    ATIVO                  BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_FORMA_PAGAMENTO
        PRIMARY KEY (ID_FORMA_PAGAMENTO),

    CONSTRAINT UK_FORMA_PAGAMENTO_NOME
        UNIQUE (NOME)
);