CREATE TABLE HISTORICOS_LANCAMENTOS (
    ID_HISTORICO           BIGINT GENERATED ALWAYS AS IDENTITY,
    ID_LANCAMENTO          BIGINT NOT NULL,
    ID_USUARIO             BIGINT NOT NULL,

    ACAO                   VARCHAR(30) NOT NULL,
    VALOR_ANTERIOR         NUMERIC(15,2),
    VALOR_NOVO             NUMERIC(15,2),
    STATUS_ANTERIOR        VARCHAR(20),
    STATUS_NOVO            VARCHAR(20),

    DESCRICAO              VARCHAR(1000),

    DATA_ACAO              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_HISTORICOS_LANCAMENTOS
        PRIMARY KEY (ID_HISTORICO),

    CONSTRAINT FK_HISTORICO_LANCAMENTO
        FOREIGN KEY (ID_LANCAMENTO)
        REFERENCES LANCAMENTOS (ID_LANCAMENTO),

    CONSTRAINT FK_HISTORICO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS (ID_USUARIO)
);