CREATE INDEX IDX_LANCAMENTO_DATA
    ON LANCAMENTOS (DATA_LANCAMENTO);

CREATE INDEX IDX_LANCAMENTO_CONTA
    ON LANCAMENTOS (ID_CONTA_FINANCEIRA);

CREATE INDEX IDX_LANCAMENTO_CONTA_DATA
    ON LANCAMENTOS (ID_CONTA_FINANCEIRA, DATA_LANCAMENTO);

CREATE INDEX IDX_LANCAMENTO_CENTRO_CUSTO
    ON LANCAMENTOS (ID_CENTRO_CUSTO);

CREATE INDEX IDX_LANCAMENTO_CLIENTE
    ON LANCAMENTOS (ID_CLIENTE);

CREATE INDEX IDX_LANCAMENTO_FORNECEDOR
    ON LANCAMENTOS (ID_FORNECEDOR);

CREATE INDEX IDX_LANCAMENTO_STATUS
    ON LANCAMENTOS (STATUS);

CREATE INDEX IDX_LANCAMENTO_TIPO
    ON LANCAMENTOS (TIPO_LANCAMENTO);

CREATE INDEX IDX_LANCAMENTO_DATA_STATUS
    ON LANCAMENTOS (DATA_LANCAMENTO, STATUS);

CREATE INDEX IDX_HISTORICO_LANCAMENTO
    ON HISTORICOS_LANCAMENTOS (ID_LANCAMENTO);

CREATE INDEX IDX_HISTORICO_DATA
    ON HISTORICOS_LANCAMENTOS (DATA_ACAO);

CREATE INDEX IDX_LOG_DATA
    ON LOGS (DATA_EVENTO);

CREATE INDEX IDX_LOG_USUARIO
    ON LOGS (ID_USUARIO);