CREATE TABLE LANCAMENTOS (
    ID_LANCAMENTO          BIGINT GENERATED ALWAYS AS IDENTITY,
    ID_CONTA_FINANCEIRA    BIGINT NOT NULL,
    ID_CONTA_CONTABIL      BIGINT NOT NULL,
    ID_CENTRO_CUSTO        BIGINT,
    ID_CLIENTE             BIGINT,
    ID_FORNECEDOR          BIGINT,
    ID_PRODUTO             BIGINT,
    ID_SERVICO             BIGINT,
    ID_FORMA_PAGAMENTO     BIGINT,

    TIPO_LANCAMENTO        VARCHAR(10) NOT NULL,
    DESCRICAO              VARCHAR(500) NOT NULL,

    VALOR                  NUMERIC(15,2) NOT NULL,

    DATA_LANCAMENTO        DATE NOT NULL,
    DATA_COMPETENCIA       DATE,
    DATA_VENCIMENTO        DATE,
    DATA_PAGAMENTO         DATE,

    STATUS                 VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',

    NUMERO_DOCUMENTO       VARCHAR(100),
    OBSERVACAO             VARCHAR(1000),

    ID_USUARIO_CRIACAO     BIGINT NOT NULL,

    DATA_CRIACAO           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO       TIMESTAMP,

    CONSTRAINT PK_LANCAMENTOS
        PRIMARY KEY (ID_LANCAMENTO),

    CONSTRAINT FK_LANCAMENTO_CONTA_FINANCEIRA
        FOREIGN KEY (ID_CONTA_FINANCEIRA)
        REFERENCES CONTA_FINANCEIRA (ID_CONTA_FINANCEIRA),

    CONSTRAINT FK_LANCAMENTO_CONTA_CONTABIL
        FOREIGN KEY (ID_CONTA_CONTABIL)
        REFERENCES CONTAS_CONTABEIS (ID_CONTA_CONTABIL),

    CONSTRAINT FK_LANCAMENTO_CENTRO_CUSTO
        FOREIGN KEY (ID_CENTRO_CUSTO)
        REFERENCES CENTROS_CUSTOS (ID_CENTRO_CUSTO),

    CONSTRAINT FK_LANCAMENTO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES (ID_CLIENTE),

    CONSTRAINT FK_LANCAMENTO_FORNECEDOR
        FOREIGN KEY (ID_FORNECEDOR)
        REFERENCES FORNECEDORES (ID_FORNECEDOR),

    CONSTRAINT FK_LANCAMENTO_PRODUTO
        FOREIGN KEY (ID_PRODUTO)
        REFERENCES PRODUTOS (ID_PRODUTO),

    CONSTRAINT FK_LANCAMENTO_SERVICO
        FOREIGN KEY (ID_SERVICO)
        REFERENCES SERVICOS (ID_SERVICO),

    CONSTRAINT FK_LANCAMENTO_FORMA_PAGAMENTO
        FOREIGN KEY (ID_FORMA_PAGAMENTO)
        REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO),

    CONSTRAINT FK_LANCAMENTO_USUARIO
        FOREIGN KEY (ID_USUARIO_CRIACAO)
        REFERENCES USUARIOS (ID_USUARIO),

    CONSTRAINT CK_LANCAMENTO_TIPO
        CHECK (TIPO_LANCAMENTO IN ('CREDITO', 'DEBITO')),

    CONSTRAINT CK_LANCAMENTO_VALOR
        CHECK (VALOR > 0),

    CONSTRAINT CK_LANCAMENTO_STATUS
        CHECK (STATUS IN (
            'PENDENTE',
            'CONFIRMADO',
            'CANCELADO',
            'ESTORNADO'
        ))
);