CREATE TABLE LOGS (
    ID_LOG                 BIGINT GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO             BIGINT,
    TIPO_EVENTO             VARCHAR(50) NOT NULL,
    ENTIDADE                VARCHAR(100),
    ID_ENTIDADE             VARCHAR(100),
    ACAO                    VARCHAR(50) NOT NULL,
    DESCRICAO               VARCHAR(1000),
    IP_ORIGEM               VARCHAR(45),
    DATA_EVENTO             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_LOGS
        PRIMARY KEY (ID_LOG),

    CONSTRAINT FK_LOG_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS (ID_USUARIO)
);