CREATE TABLE PERFIL_USUARIO (
    ID_PERFIL           BIGINT GENERATED ALWAYS AS IDENTITY,
    NOME                VARCHAR(100) NOT NULL,
    DESCRICAO           VARCHAR(500),
    ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP,

    CONSTRAINT PK_PERFIL_USUARIO
        PRIMARY KEY (ID_PERFIL),

    CONSTRAINT UK_PERFIL_USUARIO_NOME
        UNIQUE (NOME)
);