CREATE TABLE PRODUTOS (
    ID_PRODUTO          BIGINT GENERATED ALWAYS AS IDENTITY,
    NOME                VARCHAR(200) NOT NULL,
    DESCRICAO           VARCHAR(500),
    CODIGO              VARCHAR(100),
    VALOR_PADRAO        NUMERIC(15,2),
    ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP,

    CONSTRAINT PK_PRODUTOS
        PRIMARY KEY (ID_PRODUTO),

    CONSTRAINT UK_PRODUTO_CODIGO
        UNIQUE (CODIGO),

    CONSTRAINT CK_PRODUTO_VALOR
        CHECK (VALOR_PADRAO IS NULL OR VALOR_PADRAO >= 0)
);