CREATE TABLE SALDOS (
    ID_SALDO               BIGINT GENERATED ALWAYS AS IDENTITY,
    ID_CONTA_FINANCEIRA    BIGINT NOT NULL,
    DATA_SALDO             DATE NOT NULL,
    SALDO_INICIAL          NUMERIC(15,2) NOT NULL DEFAULT 0,
    TOTAL_CREDITOS         NUMERIC(15,2) NOT NULL DEFAULT 0,
    TOTAL_DEBITOS          NUMERIC(15,2) NOT NULL DEFAULT 0,
    SALDO_FINAL            NUMERIC(15,2) NOT NULL DEFAULT 0,
    DATA_ATUALIZACAO       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_SALDOS
        PRIMARY KEY (ID_SALDO),

    CONSTRAINT FK_SALDO_CONTA
        FOREIGN KEY (ID_CONTA_FINANCEIRA)
        REFERENCES CONTA_FINANCEIRA (ID_CONTA_FINANCEIRA),

    CONSTRAINT UK_SALDO_CONTA_DATA
        UNIQUE (ID_CONTA_FINANCEIRA, DATA_SALDO)
);