CREATE TABLE SERVICOS (
    ID_SERVICO          BIGINT GENERATED ALWAYS AS IDENTITY,
    NOME                VARCHAR(200) NOT NULL,
    DESCRICAO           VARCHAR(500),
    CODIGO              VARCHAR(100),
    VALOR_PADRAO        NUMERIC(15,2),
    ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP,

    CONSTRAINT PK_SERVICOS
        PRIMARY KEY (ID_SERVICO),

    CONSTRAINT UK_SERVICO_CODIGO
        UNIQUE (CODIGO),

    CONSTRAINT CK_SERVICO_VALOR
        CHECK (VALOR_PADRAO IS NULL OR VALOR_PADRAO >= 0)
);