CREATE TABLE TIPO_CONTA (
    ID_TIPO_CONTA       BIGINT GENERATED ALWAYS AS IDENTITY,
    NOME                VARCHAR(100) NOT NULL,
    DESCRICAO           VARCHAR(300),
    ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_TIPO_CONTA
        PRIMARY KEY (ID_TIPO_CONTA),

    CONSTRAINT UK_TIPO_CONTA_NOME
        UNIQUE (NOME)
);