CREATE TABLE USUARIOS (
    ID_USUARIO          BIGINT GENERATED ALWAYS AS IDENTITY,
    ID_PERFIL           BIGINT NOT NULL,
    COGNITO_SUB         VARCHAR(255) NOT NULL,
    NOME                VARCHAR(150) NOT NULL,
    EMAIL               VARCHAR(255) NOT NULL,
    CPF                 VARCHAR(14),
    TELEFONE            VARCHAR(20),
    ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CRIACAO        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP,

    CONSTRAINT PK_USUARIOS
        PRIMARY KEY (ID_USUARIO),

    CONSTRAINT FK_USUARIO_PERFIL
        FOREIGN KEY (ID_PERFIL)
        REFERENCES PERFIL_USUARIO (ID_PERFIL),

    CONSTRAINT UK_USUARIO_COGNITO
        UNIQUE (COGNITO_SUB),

    CONSTRAINT UK_USUARIO_EMAIL
        UNIQUE (EMAIL)
);